# Generated by Django 2.1.5 on 2019-10-27 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20191026_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postauthor',
            name='user',
        ),
        migrations.AlterField(
            model_name='posts',
            name='author_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cupcake_site.UserProfile'),
        ),
        migrations.DeleteModel(
            name='PostAuthor',
        ),
    ]
