# Generated by Django 2.1.5 on 2019-10-27 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20191027_0819'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Posts'},
        ),
    ]
