# Generated by Django 2.1.5 on 2019-10-27 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20191027_1838'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Posts'},
        ),
        migrations.RemoveField(
            model_name='posts',
            name='slug',
        ),
    ]
