# Generated by Django 2.1.5 on 2019-10-27 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_posts_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='post_image',
            field=models.ImageField(blank=True, upload_to='post_images/'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
