# Generated by Django 2.1.5 on 2019-11-03 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20191027_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='author_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
