# Generated by Django 2.1.5 on 2019-12-05 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20191119_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
