# Generated by Django 2.1.5 on 2019-08-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cupcake_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
