# Generated by Django 2.1.5 on 2019-08-28 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cupcake_site', '0003_auto_20190827_1515'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name_plural': 'User Profile'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(default=' ', max_length=5000),
            preserve_default=False,
        ),
    ]
