# Generated by Django 2.1.5 on 2019-08-29 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cupcake_site', '0004_auto_20190828_0917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name_plural': 'User Profiles'},
        ),
    ]
