# Generated by Django 2.1.5 on 2019-09-10 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cupcake_site', '0007_auto_20190908_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
