"""
Cassie Spalding 2140148s 

Django settings for my_diss_django_project project.

Generated by 'django-admin startproject' using Django 2.1.5.
Guided by Azzopardi & Maxwell "Tango with Django" (2019)

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

#template dir variable to join base dir so Django knows where to find my templates
TEMPLATE_DIR = os.path.join(BASE_DIR, 'templates')

#static dir variable so Django knows where to find my static media and images
STATIC_DIR = os.path.join(BASE_DIR, 'static')


#media directory root and path so Django can find media files
MEDIA_DIR = os.path.join(BASE_DIR, 'media')
MEDIA_ROOT = MEDIA_DIR
MEDIA_URL = '/media/'


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'g9$649y9cbm4lq_%9f22fvho22-y2%k4gxgk9s%)4*&4$xo)0z'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'registration',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cupcake_site',
    'posts',
    'crispy_forms',
    'coverage'
]
#use bootstrap4 templates with crispy forms
CRISPY_TEMPLATE_PACK = 'bootstrap4'


#Tango with Django page155
#If set to true, users can register
REGISTRATION_OPEN = True
#If true, logs in a user after registering
REGISTRATION_AUTO_LOGIN = True
#url Django redirects to when users have successfully logged in
LOGIN_REDIRECT_URL = 'cupcake_site:index'
#if login is unsuccessful Django redirects users to this page
LOGIN_URL ='auth_login'    

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'my_diss_django_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
         'DIRS':[TEMPLATE_DIR,],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',#added this line to process context of media files
            ],
        },
    },
]

WSGI_APPLICATION = 'my_diss_django_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
#currently an error with this when i makemigrations and migrate, saying accounts.User model not installed
#AUTH_USER_MODEL = 'accounts.User'

# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/
STATIC_URL = '/static/'
STATICFILES_DIRS = [STATIC_DIR]

#UserProfile
AUTH_PROFILE_MODULE = 'cupcake_site.UserProfile'

#will redirect to https  -  for development set to false for deployment set to True
SECURE_SSL_REDIRECT = False
